
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 * @author Femin Dharamshi
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reg_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        reg_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        reg_password = new javax.swing.JPasswordField();
        RegisterSubmit = new javax.swing.JButton();
        goToLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pocket Money Manager");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Up");

        jLabel3.setText("Name : ");
        jLabel3.setToolTipText("");

        reg_name.setToolTipText("Enter your name here");

        jLabel4.setText("User Name :");
        jLabel4.setToolTipText("");

        reg_username.setToolTipText("Enter your desired username here");
        reg_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_usernameActionPerformed(evt);
            }
        });

        jLabel5.setText("Password : ");
        jLabel5.setToolTipText("");

        reg_password.setToolTipText("Enter a password");

        RegisterSubmit.setText("Register");
        RegisterSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterSubmitActionPerformed(evt);
            }
        });

        goToLogin.setText("Login");
        goToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Femin Dharamshi - SE3 - Roll No. 09");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegisterSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(goToLogin))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(reg_password)
                        .addComponent(reg_username, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                    .addComponent(reg_name, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reg_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(reg_username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_usernameActionPerformed

    private void goToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginActionPerformed
        // TODO add your handling code here:
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        loginFrame.setTitle("Pocket Money Manager");
        dispose();
    }//GEN-LAST:event_goToLoginActionPerformed

    private void RegisterSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterSubmitActionPerformed

        try
        {
            Boolean uniqueUser = true;
            String Name = reg_name.getText().toString();
            String UserName = reg_username.getText().toString();
            String Password = reg_password.getText().toString();
            
            if(Name.length()>0 && UserName.length()>0 && Password.length()>0)
            {
                if(isAlpha(UserName))
                {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/java_app","root","");
                    Statement st=conn.createStatement();

                    ResultSet rs = st.executeQuery ("SELECT * FROM users_details");

                    while(rs.next())
                    {
                        if(rs.getString(4).equalsIgnoreCase(UserName))
                            uniqueUser = false;
                    }

                    //Go Ahead only if the userName is unique and not already in database.

                    if(uniqueUser)
                    {
                        String query="CREATE TABLE "+UserName+" (id int NOT NULL AUTO_INCREMENT PRIMARY KEY ,amount double,type text, date text)";
                        st.execute(query);
                        
                        query = "INSERT INTO users_details (name, pswd, username) VALUES (?,?,?)";
                        PreparedStatement stmt=conn.prepareStatement(query);  
                        stmt.setString(1, Name);
                        stmt.setString(2, Password);
                        stmt.setString(3, UserName);
                        
                        stmt.execute();
                        
                        JOptionPane.showMessageDialog(this, "New User Created Successfully!", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                        reg_name.setText("");
                        reg_username.setText("");
                        reg_password.setText("");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "User Name is already taken. Try another one.", "User Name Not Available",
                        JOptionPane.ERROR_MESSAGE);
                    }
                }else
                {
                    JOptionPane.showMessageDialog(this, "Only alphabets allowed in User Name.", "Incorrect Details",
                        JOptionPane.ERROR_MESSAGE);
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "Please enter the details", "Error!",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error Occurred While Creating a new user."+e.getMessage(), "Error!",
            JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
//        try
//        {
//            
//            String query="CREATE TABLE "+ userName_reg.getText().toString() +" (AccNo int,CustName text,balance float)";
//            st.execute(query);
//        }catch(Exception e)
//        {
//            
//        }
    }//GEN-LAST:event_RegisterSubmitActionPerformed

    public boolean isAlpha(String name) {
        char[] chars = name.toCharArray();

        for (char c : chars) {
            if(!Character.isLetter(c)) {
                return false;
            }
        }

        return true;
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUp SU = new SignUp();
                SU.setVisible(true);
                SU.setTitle("Pocket Money Manager");
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterSubmit;
    private javax.swing.JButton goToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField reg_name;
    private javax.swing.JPasswordField reg_password;
    private javax.swing.JTextField reg_username;
    // End of variables declaration//GEN-END:variables
}
